homepage: https://example.com/mini-crs
primary_contact: you@example.com
language: c++
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined
architectures:
  - x86_64
main_repo: https://example.com/mini-crs
